import {
  pgTable,
  text,
  integer,
  real,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

/**
 * Businesses
 *
 * A business belongs to a Clerk-authenticated user.
 */
export const businesses = pgTable(
  "businesses",
  {
    id: text("id").primaryKey(),

    clerkUserId: text("clerk_user_id").notNull(),

    businessName: text("business_name").notNull(),

    businessType: text("business_type").notNull(),

    industry: text("industry").notNull(),

    state: text("state").notNull(),

    createdAt: timestamp("created_at").defaultNow().notNull(),

    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => ({
    clerkUserIdIdx: index("businesses_clerk_user_id_idx").on(
      table.clerkUserId
    ),
  })
);


/**
 * Energy records
 *
 * Stores the energy information submitted by a business.
 */
export const energyRecords = pgTable(
  "energy_records",
  {
    id: text("id").primaryKey(),

    businessId: text("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "cascade",
      }),

    year: integer("year").notNull(),

    month: integer("month").notNull(),

    quarter: integer("quarter").notNull(),

    energySource: text("energy_source").notNull(),

    electricityBill: real("electricity_bill").notNull(),

    dieselCost: real("diesel_cost").notNull(),

    petrolCost: real("petrol_cost").notNull(),

    totalEnergyCost: real("total_energy_cost").notNull(),

    energyConsumptionKwh: real("energy_consumption_kwh").notNull(),

    fuelConsumptionLiters: real("fuel_consumption_liters").notNull(),

    generatorHours: real("generator_hours").notNull(),

    gridHours: real("grid_hours").notNull(),

    outageHours: real("outage_hours").notNull(),

    operatingHours: real("operating_hours").notNull(),

    employeeCount: integer("employee_count").notNull(),

    employees: integer("employees").notNull(),

    occupancyRate: real("occupancy_rate").notNull(),

    floorAreaSqm: real("floor_area_sqm").notNull(),

    solarCapacityKw: real("solar_capacity_kw").notNull(),

    renewableEnergyPercentage: real(
      "renewable_energy_percentage"
    ).notNull(),

    maintenanceCost: real("maintenance_cost").notNull(),

    monthlyRevenue: real("monthly_revenue").notNull(),

    energyCostPerEmployee: real(
      "energy_cost_per_employee"
    ).notNull(),

    costPerKwh: real("cost_per_kwh").notNull(),

    averageMonthlyEnergyCost: real(
      "average_monthly_energy_cost"
    ).notNull(),

    energyEfficiencyScore: real(
      "energy_efficiency_score"
    ).notNull(),

    generatorDependency: real(
      "generator_dependency"
    ).notNull(),

    revenueEnergyRatio: real(
      "revenue_energy_ratio"
    ).notNull(),

    outageSeverity: real("outage_severity").notNull(),

    weatherAvgTemp: real("weather_avg_temp").notNull(),

    estimatedCarbonIntensity: real(
      "estimated_carbon_intensity"
    ).notNull(),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    businessIdIdx: index("energy_records_business_id_idx").on(
      table.businessId
    ),

    periodIdx: index("energy_records_period_idx").on(
      table.businessId,
      table.year,
      table.month
    ),

    businessPeriodUnique: uniqueIndex(
      "energy_records_business_year_month_unique"
    ).on(table.businessId, table.year, table.month),
  })
);


/**
 * Predictions
 *
 * Stores every prediction generated by the ML service.
 */
export const predictions = pgTable(
  "predictions",
  {
    id: text("id").primaryKey(),

    businessId: text("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "cascade",
      }),

    energyRecordId: text("energy_record_id").references(
      () => energyRecords.id,
      {
        onDelete: "set null",
      }
    ),

    predictedNextMonthEnergyCost: real(
      "predicted_next_month_energy_cost"
    ).notNull(),

    predictedChange: real("predicted_change"),

    predictedChangePercent: real(
      "predicted_change_percent"
    ),

    predictedCostPerEmployee: real(
      "predicted_cost_per_employee"
    ),

    predictedCostPerKwh: real(
      "predicted_cost_per_kwh"
    ),

    generatorDependencyPercent: real(
      "generator_dependency_percent"
    ),

    outageHours: real("outage_hours"),

    predictedEnergyCostAsPercentOfRevenue: real(
      "predicted_energy_cost_as_percent_of_revenue"
    ),

    model: text("model").notNull(),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    businessIdIdx: index("predictions_business_id_idx").on(
      table.businessId
    ),

    createdAtIdx: index("predictions_created_at_idx").on(
      table.createdAt
    ),
  })
);


/**
 * AI insights
 *
 * Stores the structured Gemini response associated
 * with a prediction.
 */
export const insights = pgTable(
  "insights",
  {
    id: text("id").primaryKey(),

    businessId: text("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "cascade",
      }),

    predictionId: text("prediction_id")
      .notNull()
      .references(() => predictions.id, {
        onDelete: "cascade",
      }),

    summary: text("summary").notNull(),

    keyInsights: jsonb("key_insights").notNull(),

    recommendations: jsonb("recommendations").notNull(),

    riskLevel: text("risk_level").notNull(),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => ({
    businessIdIdx: index("insights_business_id_idx").on(
      table.businessId
    ),

    predictionIdIdx: index("insights_prediction_id_idx").on(
      table.predictionId
    ),
  })
);


/* -------------------------------------------------------------------------- */
/* Relations                                                                  */
/* -------------------------------------------------------------------------- */

export const businessesRelations = relations(
  businesses,
  ({ many }) => ({
    energyRecords: many(energyRecords),

    predictions: many(predictions),

    insights: many(insights),
  })
);


export const energyRecordsRelations = relations(
  energyRecords,
  ({ one, many }) => ({
    business: one(businesses, {
      fields: [energyRecords.businessId],
      references: [businesses.id],
    }),

    predictions: many(predictions),
  })
);


export const predictionsRelations = relations(
  predictions,
  ({ one, many }) => ({
    business: one(businesses, {
      fields: [predictions.businessId],
      references: [businesses.id],
    }),

    energyRecord: one(energyRecords, {
      fields: [predictions.energyRecordId],
      references: [energyRecords.id],
    }),

    insights: many(insights),
  })
);


export const insightsRelations = relations(
  insights,
  ({ one }) => ({
    business: one(businesses, {
      fields: [insights.businessId],
      references: [businesses.id],
    }),

    prediction: one(predictions, {
      fields: [insights.predictionId],
      references: [predictions.id],
    }),
  })
);